### ISSUE TITLE
Dependencies could use some inheritance/grouping

### ISSUE THREAD

**Issue by Destroy666x** [doctrine/DoctrineFixturesBundle#272]
Because right now they aren't really "smarter" as advertised in docs.

Example:
`FoodFixtureLoader` is abstract has children `ChineseFoodFixtureLoader` and `ItalianFoodFixtureLoader`
`CookFixtureLoader` is abstract and has multiple children that load references of food from either Chinese/Italian or both depending on (re)introduced groups.

There's no way to point at `FoodFixtureLoader` as a common dependency because the code doesn't look at inheritance, only the exact class.

But what would be perfect I think is something like:
```php
public function getDependenciesForGroups(): array
{
    return [
        ChineseFoodFixtureLoader::class => ['chineseCooks', 'cooks'],
        ItalianFoodFixtureLoader::class => ['italianCooks', 'cooks'],
    ];
}
```

I could work on a PR if you agree to any solution.

**Comment by alcaeus** [comment]
I'm not sure I understand your problem, but why wouldn't the `ChineseFoodFixtureLoader` have a dependency on `ChineseCookFixtureLoader` and `ItalianFoodFixtureLoader` on `ItalianCookFixtureLoader`? From what I can see this can easily be solved with the dependency system that is in place now.

**Comment by Destroy666x** [comment]
Not quite. Maybe a better example since the last one was rushed.

2 `AreaFixtureLoader` children: `CountryAreasFixtureLoader`, `CapitalAreasFixtureLoader` - one loads areas from the whole country, the other only from the capital.
Multiple `PlaceFixtureLoader` children, e.g.  `CapitalPlacesFixtureLoader`, which loads places only for the capital and is in multiple fixture groups, including ones that load `CountryAreasFixtureLoader` rather than `CapitalAreasFixtureLoader`.

Yes, I could separate `CapitalPlacesFixtureLoader` into 2 weirdly named classes with different dependencies and groups, but I think that's much more counterintuitive than just providing for which groups which dependencies are required.

**Comment by alcaeus** [comment]
I stand by my original comment. Here's how the dependencies should be configured:

* `CapitalAreasFixtureLoader`: ~
* `CapitalPlacesFixtureLoader`: `CapitalAreasFixtureLoader`
* `CountryAreasFixtureLoader`: `CapitalAreasFixtureLoader`
* `CountryPlacesFixtureLoader`: `CapitalPlacesFixtureLoader `, `CountryAreasFixtureLoader`

Regardless of whether you're loading only capital areas or the whole country stuff, you'll want the capital areas to be the same since they're used in `CapitalPlacesFixtureLoader`. That dependency chain ensures a consistent order of fixtures and also ensures that you're not trying to load fixtures for something that isn't there to begin with.

Of course, this all assumes that your capital areas/places are a subset of country areas/places and not duplicated within the country fixtures. If they are, you'll need to fix that first, not work around it in a library. I don't think this is something we want to fix here.

**Comment by Destroy666x** [comment]
As you wish. But you're basically forcing to use `getOrder` since in reality with many more classes this approach gets quite messy unnecessarily.

And you missed the "the ones in capital are different" part because your assumption is incorrect. Thereby your other assumption about duplicates is also incorrect. They're different to the point where they can't be in the same fixture file/dependencies, but not different enough to matter for the places.
